openapi: 3.1.0
info:
  title: Endpoint для приема входящих сообщений
  description: |-
    API для приема входящих сообщений
  termsOfService: http://localhost/
  version: 1.0.0
servers:
  - url: http://localhost:8081/api/v1
tags:
  - name: message
    description: Endpoint для приема входящих сообщений
paths:
  /message/:
    post:
      tags:
        - message
      summary: Новое сообщение
      description: Создание новой категории
      operationId: processMessages
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
      responses:
        '200':
          description: Успешное выполнение
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '400':
          description: ошибка запроса
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Errors'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
components:
  schemas:
    Errors:
      type: object
      properties:
        errors:
          type: object
          additionalProperties:
            example: Описание ошибки
            type: string
    MessageResponse:
      type: object
      properties:
        status:
          title: Статус
          type: string
          example: ACCEPTED
        message:
          type: object
          additionalProperties:
            type: string
    Message:
      type: object
      title: Сообщение
      properties:
        guid:
          title: guid сообщения
          type: string
          format: uuid
        game:
          title: guid игры
          type: string
          format: uuid
        object:
          title: id объекта
          type: integer
          format: int64
          example: 1
        action:
          title: id команды
          type: integer
          format: int64
          example: 1
        args:
          additionalProperties:
            type: string